"""Lightweight, exploratory data-attribution proxy.

Inspired by Chen, Luo & Pan (2026) "Mechanistic Data Attribution" (MDA), but
explicitly NOT a faithful reimplementation -- MDA uses proper influence
functions (inverse-Hessian-vector products) at LLM/Pythia scale across a
full training trajectory. What's implemented here is a much cruder,
single-checkpoint TracIn-style gradient-dot-product proxy computed on a
random subsample of a generation's training pool, which is tractable on
CPU for a course project:

    influence(train_example) ~= grad_theta L(train_example) . grad_theta L(val_batch)

A positive score means that example's gradient points in roughly the same
direction as reducing validation loss on the real task (i.e. it "helped");
negative means it pointed the model away from the real task. This is
explicitly exploratory/approximate -- treat signs and rough magnitudes as
suggestive, not as calibrated influence estimates.

Alongside influence, `label_consistency_rate` is a data-side (model-free)
quality measure specific to this task: for real data, every repeated
occurrence of a symbol in a context MUST carry the same label (that's how
data.py constructs sequences), so consistency is always 1.0. For synthetic
data autoregressively generated by an imperfect extended-variant model,
the model can (and, once collapse sets in, does) assign a different label
to a later occurrence of an already-seen symbol -- a direct, interpretable
symptom of degraded induction that can be measured without running the
model at all, and correlated against influence scores or generation index.
"""

from __future__ import annotations

import random

import torch

from data import collate_batch
from metrics import compute_losses


def flatten_grad(model: torch.nn.Module) -> torch.Tensor:
    return torch.cat([p.grad.reshape(-1) for p in model.parameters() if p.grad is not None])


def _example_gradient(model, item: dict, extended: bool) -> tuple[torch.Tensor, float]:
    batch = collate_batch([item])
    model.zero_grad()
    out = model(batch["symbol_tokens"], batch["label_tokens"])
    loss_out = compute_losses(out, batch, extended)
    loss_out.total_loss.backward()
    return flatten_grad(model).clone(), loss_out.total_loss.item()


def compute_example_influences(
    model: torch.nn.Module,
    train_items: list[dict],
    val_batch: dict,
    extended: bool,
    n_sample: int = 300,
    seed: int = 0,
) -> list[dict]:
    """TracIn-lite influence of a random subsample of `train_items` on
    `val_batch`'s loss, evaluated at the model's current (single) checkpoint."""
    model.eval()
    rng = random.Random(seed)
    idx = rng.sample(range(len(train_items)), min(n_sample, len(train_items)))

    model.zero_grad()
    out = model(val_batch["symbol_tokens"], val_batch["label_tokens"])
    val_loss_out = compute_losses(out, val_batch, extended)
    val_loss_out.total_loss.backward()
    val_grad = flatten_grad(model).clone()

    results = []
    for i in idx:
        item = train_items[i]
        g, train_loss = _example_gradient(model, item, extended)
        influence = torch.dot(g, val_grad).item()
        results.append({
            "index": i,
            "influence": influence,
            "train_loss": train_loss,
            "label_consistency": label_consistency_rate([item]),
        })
    model.zero_grad()
    return results


def label_consistency_rate(items: list[dict]) -> float:
    """Fraction of repeated symbol occurrences (across a set of items) whose
    label matches that symbol's FIRST occurrence in the same context. 1.0
    for well-formed real data by construction; can drop below 1.0 for
    synthetic data generated by an extended-variant model that has not
    perfectly learned to copy a consistent label for a repeated symbol."""
    total, consistent = 0, 0
    for item in items:
        symbols = item["symbol_tokens"][:-1].tolist()  # context symbols only
        labels = item["label_tokens"].tolist()
        first_label = {}
        for s, l in zip(symbols, labels):
            if s not in first_label:
                first_label[s] = l
            else:
                total += 1
                if l == first_label[s]:
                    consistent += 1
    return consistent / total if total > 0 else float("nan")
